// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: chart/chart.proto

package chart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"name" yaml:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" yaml:"name"`
	// @gotags: json:"fullName" yaml:"fullName"
	FullName string `protobuf:"bytes,2,opt,name=fullName,proto3" json:"fullName" yaml:"fullName"`
	// @gotags: json:"version" yaml:"version"
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version" yaml:"version"`
	// @gotags: json:"command" yaml:"command"
	Command string `protobuf:"bytes,4,opt,name=command,proto3" json:"command" yaml:"command"`
	// @gotags: json:"moredVersion" yaml:"moredVersion"
	MoredVersion string `protobuf:"bytes,5,opt,name=moredVersion,proto3" json:"moredVersion" yaml:"moredVersion"`
	// @gotags: json:"os" yaml:"os"
	Os []string `protobuf:"bytes,6,rep,name=os,proto3" json:"os" yaml:"os"`
	// @gotags: json:"arch" yaml:"arch"
	Arch []string `protobuf:"bytes,7,rep,name=arch,proto3" json:"arch" yaml:"arch"`
	// @gotags: json:"effects" yaml:"effects"
	Effects []int64 `protobuf:"varint,8,rep,packed,name=effects,proto3" json:"effects" yaml:"effects"`
	// @gotags: json:"depTools" yaml:"depTools"
	DepTools []*Dependency `protobuf:"bytes,9,rep,name=depTools,proto3" json:"depTools" yaml:"depTools"`
	// @gotags: json:"depSuites" yaml:"depSuites"
	DepSuites []*Dependency `protobuf:"bytes,10,rep,name=depSuites,proto3" json:"depSuites" yaml:"depSuites"`
	// @gotags: json:"metadata" yaml:"metadata"
	Metadata *Metadata `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata" yaml:"metadata"`
}

func (x *Chart) Reset() {
	*x = Chart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chart_chart_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Chart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart) ProtoMessage() {}

func (x *Chart) ProtoReflect() protoreflect.Message {
	mi := &file_chart_chart_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart.ProtoReflect.Descriptor instead.
func (*Chart) Descriptor() ([]byte, []int) {
	return file_chart_chart_proto_rawDescGZIP(), []int{0}
}

func (x *Chart) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chart) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Chart) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Chart) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Chart) GetMoredVersion() string {
	if x != nil {
		return x.MoredVersion
	}
	return ""
}

func (x *Chart) GetOs() []string {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *Chart) GetArch() []string {
	if x != nil {
		return x.Arch
	}
	return nil
}

func (x *Chart) GetEffects() []int64 {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *Chart) GetDepTools() []*Dependency {
	if x != nil {
		return x.DepTools
	}
	return nil
}

func (x *Chart) GetDepSuites() []*Dependency {
	if x != nil {
		return x.DepSuites
	}
	return nil
}

func (x *Chart) GetMetadata() *Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Dependency struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"name" yaml:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" yaml:"name"`
	// @gotags: json:"version" yaml:"version"
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version" yaml:"version"`
	// @gotags: json:"repo" yaml:"repo"
	Repo string `protobuf:"bytes,3,opt,name=repo,proto3" json:"repo" yaml:"repo"`
}

func (x *Dependency) Reset() {
	*x = Dependency{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chart_chart_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dependency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dependency) ProtoMessage() {}

func (x *Dependency) ProtoReflect() protoreflect.Message {
	mi := &file_chart_chart_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dependency.ProtoReflect.Descriptor instead.
func (*Dependency) Descriptor() ([]byte, []int) {
	return file_chart_chart_proto_rawDescGZIP(), []int{1}
}

func (x *Dependency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Dependency) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Dependency) GetRepo() string {
	if x != nil {
		return x.Repo
	}
	return ""
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"icon" yaml:"icon"
	Icon string `protobuf:"bytes,1,opt,name=icon,proto3" json:"icon" yaml:"icon"`
	// @gotags: json:"description" yaml:"description"
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description" yaml:"description"`
	// @gotags: json:"digest" yaml:"digest"
	Digest string `protobuf:"bytes,3,opt,name=digest,proto3" json:"digest" yaml:"digest"`
	// @gotags: json:"keywords" yaml:"keywords"
	Keywords []string `protobuf:"bytes,4,rep,name=keywords,proto3" json:"keywords" yaml:"keywords"`
	// @gotags: json:"maintainers" yaml:"maintainers"
	Maintainers []*Maintainer `protobuf:"bytes,5,rep,name=maintainers,proto3" json:"maintainers" yaml:"maintainers"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chart_chart_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_chart_chart_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_chart_chart_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *Metadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Metadata) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *Metadata) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *Metadata) GetMaintainers() []*Maintainer {
	if x != nil {
		return x.Maintainers
	}
	return nil
}

type Maintainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"name" yaml:"name"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name" yaml:"name"`
	// @gotags: json:"email" yaml:"email"
	Email string `protobuf:"bytes,2,opt,name=email,proto3" json:"email" yaml:"email"`
	// @gotags: json:"home" yaml:"home"
	Home string `protobuf:"bytes,3,opt,name=home,proto3" json:"home" yaml:"home"`
}

func (x *Maintainer) Reset() {
	*x = Maintainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chart_chart_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Maintainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maintainer) ProtoMessage() {}

func (x *Maintainer) ProtoReflect() protoreflect.Message {
	mi := &file_chart_chart_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maintainer.ProtoReflect.Descriptor instead.
func (*Maintainer) Descriptor() ([]byte, []int) {
	return file_chart_chart_proto_rawDescGZIP(), []int{3}
}

func (x *Maintainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Maintainer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Maintainer) GetHome() string {
	if x != nil {
		return x.Home
	}
	return ""
}

var File_chart_chart_proto protoreflect.FileDescriptor

var file_chart_chart_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x72, 0x64, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x22, 0xe6,
	0x02, 0x0a, 0x05, 0x43, 0x68, 0x61, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x22, 0x0a, 0x0c,
	0x6d, 0x6f, 0x72, 0x65, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6d, 0x6f, 0x72, 0x65, 0x64, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73,
	0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x63, 0x68, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04,
	0x61, 0x72, 0x63, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x03, 0x52, 0x07, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x73, 0x12, 0x31,
	0x0a, 0x08, 0x64, 0x65, 0x70, 0x54, 0x6f, 0x6f, 0x6c, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x6d, 0x72, 0x64, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x44, 0x65, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x08, 0x64, 0x65, 0x70, 0x54, 0x6f, 0x6f, 0x6c,
	0x73, 0x12, 0x33, 0x0a, 0x09, 0x64, 0x65, 0x70, 0x53, 0x75, 0x69, 0x74, 0x65, 0x73, 0x18, 0x0a,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x72, 0x64, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74,
	0x2e, 0x44, 0x65, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x6e, 0x63, 0x79, 0x52, 0x09, 0x64, 0x65, 0x70,
	0x53, 0x75, 0x69, 0x74, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6d, 0x72, 0x64, 0x2e, 0x63,
	0x68, 0x61, 0x72, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x4e, 0x0a, 0x0a, 0x44, 0x65, 0x70, 0x65, 0x6e,
	0x64, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x72, 0x65, 0x70, 0x6f, 0x22, 0xad, 0x01, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69,
	0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x37,
	0x0a, 0x0b, 0x6d, 0x61, 0x69, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x72, 0x64, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e,
	0x4d, 0x61, 0x69, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x52, 0x0b, 0x6d, 0x61, 0x69, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x22, 0x4a, 0x0a, 0x0a, 0x4d, 0x61, 0x69, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x68, 0x6f, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68,
	0x6f, 0x6d, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x6d, 0x72, 0x64, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x74,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chart_chart_proto_rawDescOnce sync.Once
	file_chart_chart_proto_rawDescData = file_chart_chart_proto_rawDesc
)

func file_chart_chart_proto_rawDescGZIP() []byte {
	file_chart_chart_proto_rawDescOnce.Do(func() {
		file_chart_chart_proto_rawDescData = protoimpl.X.CompressGZIP(file_chart_chart_proto_rawDescData)
	})
	return file_chart_chart_proto_rawDescData
}

var file_chart_chart_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_chart_chart_proto_goTypes = []interface{}{
	(*Chart)(nil),      // 0: mrd.chart.Chart
	(*Dependency)(nil), // 1: mrd.chart.Dependency
	(*Metadata)(nil),   // 2: mrd.chart.Metadata
	(*Maintainer)(nil), // 3: mrd.chart.Maintainer
}
var file_chart_chart_proto_depIdxs = []int32{
	1, // 0: mrd.chart.Chart.depTools:type_name -> mrd.chart.Dependency
	1, // 1: mrd.chart.Chart.depSuites:type_name -> mrd.chart.Dependency
	2, // 2: mrd.chart.Chart.metadata:type_name -> mrd.chart.Metadata
	3, // 3: mrd.chart.Metadata.maintainers:type_name -> mrd.chart.Maintainer
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_chart_chart_proto_init() }
func file_chart_chart_proto_init() {
	if File_chart_chart_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chart_chart_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Chart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chart_chart_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dependency); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chart_chart_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chart_chart_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Maintainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chart_chart_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chart_chart_proto_goTypes,
		DependencyIndexes: file_chart_chart_proto_depIdxs,
		MessageInfos:      file_chart_chart_proto_msgTypes,
	}.Build()
	File_chart_chart_proto = out.File
	file_chart_chart_proto_rawDesc = nil
	file_chart_chart_proto_goTypes = nil
	file_chart_chart_proto_depIdxs = nil
}
