// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.1
// source: chart/index.proto

package chart

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Index struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: json:"version" yaml:"version"
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version" yaml:"version"`
	// @gotags: json:"generated" yaml:"generated"
	Generated *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=generated,proto3" json:"generated" yaml:"generated"`
	// @gotags: json:"suites" yaml:"suites"
	Suites []*Chart `protobuf:"bytes,3,rep,name=suites,proto3" json:"suites" yaml:"suites"`
	// @gotags: json:"toolkits" yaml:"toolkits"
	Toolkits []*Chart `protobuf:"bytes,4,rep,name=toolkits,proto3" json:"toolkits" yaml:"toolkits"`
}

func (x *Index) Reset() {
	*x = Index{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chart_index_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_chart_index_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_chart_index_proto_rawDescGZIP(), []int{0}
}

func (x *Index) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Index) GetGenerated() *timestamppb.Timestamp {
	if x != nil {
		return x.Generated
	}
	return nil
}

func (x *Index) GetSuites() []*Chart {
	if x != nil {
		return x.Suites
	}
	return nil
}

func (x *Index) GetToolkits() []*Chart {
	if x != nil {
		return x.Toolkits
	}
	return nil
}

var File_chart_index_proto protoreflect.FileDescriptor

var file_chart_index_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x72, 0x64, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x11, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2f, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xb3, 0x01, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x28, 0x0a, 0x06, 0x73, 0x75, 0x69, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x6d, 0x72, 0x64, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x68, 0x61,
	0x72, 0x74, 0x52, 0x06, 0x73, 0x75, 0x69, 0x74, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x08, 0x74, 0x6f,
	0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d,
	0x72, 0x64, 0x2e, 0x63, 0x68, 0x61, 0x72, 0x74, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x52, 0x08,
	0x74, 0x6f, 0x6f, 0x6c, 0x6b, 0x69, 0x74, 0x73, 0x42, 0x0b, 0x5a, 0x09, 0x6d, 0x72, 0x64, 0x2f,
	0x63, 0x68, 0x61, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chart_index_proto_rawDescOnce sync.Once
	file_chart_index_proto_rawDescData = file_chart_index_proto_rawDesc
)

func file_chart_index_proto_rawDescGZIP() []byte {
	file_chart_index_proto_rawDescOnce.Do(func() {
		file_chart_index_proto_rawDescData = protoimpl.X.CompressGZIP(file_chart_index_proto_rawDescData)
	})
	return file_chart_index_proto_rawDescData
}

var file_chart_index_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chart_index_proto_goTypes = []interface{}{
	(*Index)(nil),                 // 0: mrd.chart.Index
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*Chart)(nil),                 // 2: mrd.chart.Chart
}
var file_chart_index_proto_depIdxs = []int32{
	1, // 0: mrd.chart.Index.generated:type_name -> google.protobuf.Timestamp
	2, // 1: mrd.chart.Index.suites:type_name -> mrd.chart.Chart
	2, // 2: mrd.chart.Index.toolkits:type_name -> mrd.chart.Chart
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chart_index_proto_init() }
func file_chart_index_proto_init() {
	if File_chart_index_proto != nil {
		return
	}
	file_chart_chart_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chart_index_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Index); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chart_index_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chart_index_proto_goTypes,
		DependencyIndexes: file_chart_index_proto_depIdxs,
		MessageInfos:      file_chart_index_proto_msgTypes,
	}.Build()
	File_chart_index_proto = out.File
	file_chart_index_proto_rawDesc = nil
	file_chart_index_proto_goTypes = nil
	file_chart_index_proto_depIdxs = nil
}
